server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrWorker?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: d94ed3838
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
