server:
  port: 8001

spring:
  application:
    name: hr-worker
  datasource:
    url: jdbc:mysql://localhost:3306/hrWorker?useTimezone=true
    username: root
    password: d94ed3838
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka