server:
  port: 8888

spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Matheus-FSantos/human-resources-microservice-config-server
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
